version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt-get update -y
      - npm install
  prebuild:
    commands:
      - npm run test
  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/**/*
    - package.json